### ISSUE TITLE
提示错误“Symbol’s function definition is void: string-join”

### ISSUE THREAD

**Issue by roife** [casouri/nerdtab#3]
安装完按`M-x nerdtab-mode`提示`Symbol’s function definition is void: string-join`

**Comment by roife** [comment]
实测可以改成`combine-and-quote-strings`

**Comment by casouri** [comment]
Emmmm.....  `string-join` belongs to `subr-x.el`, which is a part of GNU Emacs. It should be available. What is your Emacs version?

**Comment by roife** [comment]
Emacs-Plus(from Homebrew) on macOS High Sierra 10.13.6
version: GNU emacs 26.1

**Comment by casouri** [comment]
Thanks, can you confirm the fix?

**Comment by roife** [comment]
Yeah, it works well.
